### ISSUE TITLE
add ctrl + enter keyboard shortcut to solve tasks

### ISSUE THREAD

**Issue by LukeberryPi** [LukeberryPi/phived#1]
currently, when you are done with a task, there is no way to get rid of it through the keyboard. the only way is hovering over the input with a mouse, and clicking the done button.

my suggestion is that, when user focus is on one of the tasks + the task is not empty, pressing ctrl + enter calls handleDone and the task list gets updated accordingly.

this is the function in question:

![image](https://user-images.githubusercontent.com/98068247/225653658-1c7c59dc-2f98-4881-8bc8-b8e978a3b369.png)

**Comment by romulorod** [comment]
https://github.com/LukeberryPi/phived/pull/4
