### ISSUE TITLE
Avoid multiples index

### ISSUE THREAD

**Issue by vit0rr** [LukeberryPi/phived#11]
Why did you decide to have a multiples index to export something?
Having an index to every component does not look good, and it is an anti-pattern - avoid multiple files with the same name. It's a bad DX to debug something or learn the code-base

What do you think about it? Can I fix it?

**Comment by vit0rr** [comment]
![image](https://user-images.githubusercontent.com/70543018/226131352-2a14c0bb-6866-431c-bbc5-c3c0b26c7bf8.png)

**Comment by LukeberryPi** [comment]
i just mimicked the structure that is used at my work codebase.

absolutely you can fix it, thanks for the heads up, curious to see the PR.
