### ISSUE TITLE
Spaces are considered as tasks

### ISSUE THREAD

**Issue by Nick-Gabe** [LukeberryPi/phived#16]
If I put spaces " " in any of the task fields, it will be considered as a task and will be appearing as a notification in the top, also having the "done?" option. Is this intentional?

![image](https://user-images.githubusercontent.com/42651514/226178441-40c45f08-9bd4-474d-9f45-98c3bc5209d9.png)

**Comment by LukeberryPi** [comment]
nope, not intentional.

adding a isEmpty function that also checks for space-filled strings should be enough, correct?

you may go ahead :)
