### ISSUE TITLE
We should center tasks in a context instead of passing as props

### ISSUE THREAD

**Issue by Nick-Gabe** [LukeberryPi/phived#21]
By centering the tasks in a context, we would be able to create specific functions for it almost like methods, without needing to rely on passing props for every component that wants the data or creating custom functions in separate components.

Also their types would be centered, so if at any point someone decides to change the task type from string to Object or the task quantity from 5 to 6, it would update their dependencies aswell. (ts is lovely)

**Comment by LukeberryPi** [comment]
is being debated at https://github.com/LukeberryPi/phived/pull/22
