### ISSUE TITLE
Configure eslint to standardize code

### ISSUE THREAD

**Issue by Nick-Gabe** [LukeberryPi/phived#23]
I love how the project is getting a lot of help from the community, but currently we don't have any tool to provide a code checking to make sure everyone follow the same code style. For example someone can use double quotes, while other prople use single quotes, while another use crasis and so on...

I think we can configure eslint rules for everyone to follow, along with using [lint-staged](https://www.npmjs.com/package/lint-staged) and [husky](https://www.npmjs.com/package/husky) to do that automatically whenever I submit a commit.

### Useful Links
[Lint Staged and Husky](https://valchan.com.br/lint-staged-husky/)
[Lint staged README](https://github.com/okonet/lint-staged/blob/master/README.md)
[Setting ESLint on a React Typescript project](https://andrebnassis.medium.com/setting-eslint-on-a-react-typescript-project-2021-1190a43ffba)

**Comment by nidib** [comment]
Are you working on a PR to solve this? I can get it started. Adding .editorconfig is also a nice touch.

Since my personal preference and VSCode settings are all set for 4 tabs with no space substitution, I have to manually tab when working on this project

**Comment by Nick-Gabe** [comment]
@nidib Sure, go ahead! I think we can use Airbnb's as a base, and get some other rules based on what we already have:
- double quotes
- semicolon
- no default export
-  Arrow parens always
- no implicit any
and maybe others that I didnt notice
