### ISSUE TITLE
Add feature to move task order

### ISSUE THREAD

**Issue by rodolformartins** [LukeberryPi/phived#25]
Add feature to move task order to up or down.

**Comment by LukeberryPi** [comment]
this is something we want to pursue. will line this up on the roadmap

**Comment by Chicarelli** [comment]
How would you like this to be implemented?

**Comment by LukeberryPi** [comment]
i'm looking into https://github.com/atlassian/react-beautiful-dnd for this

**Comment by jvolima** [comment]
This is a cool feature, I've used this lib once, I can try to do it.
I just didn't understand one thing, does this orange border have to be between all the tasks that the user filled out?

**Comment by LukeberryPi** [comment]
closed at https://github.com/LukeberryPi/phived/pull/42
