### ISSUE TITLE
Add descriptive title tag and a h1

### ISSUE THREAD

**Issue by Fearinn** [LukeberryPi/phived#27]
A descriptive title tag is important for SEO and UX. It helps crawlers and people to understand the content of the page. My suggestion would be something like "Phived - An Anti-Procrastination To-Do List". 

A h1 tag would be a good addition too. It could replace the current "phived" span, although, in this case, keyboard navigators could accidentally skip the form. Simpler solution would be to move "phived" above the form.

For reference: 
https://www.screamingfrog.co.uk/learn-seo/page-title/
https://www.semrush.com/blog/h1-tag/

**Comment by LukeberryPi** [comment]
hey fearinn! agreed, title could be a lot more descriptive. feel free to open a PR that changes it from it's current variations:

- **no active task**, from "phived" to "phived - the anti-procrastination to-do list"
- **with active tasks**, from "[<number of active tasks>] phived" to "[<number of active tasks>] phived - the anti-procrastination to-do list"

please be mindful that this repo's copy is entirely lowercase. catch you soon!
