### ISSUE TITLE
ERR_CONECTION_REFUSED

### ISSUE THREAD

**Issue by LukeberryPi** [LukeberryPi/phived#28]
this error has been plaguing us since day 1. from what i could observe it happens throughout the day, regardless of code changes. as in, it doesn't matter if we have just merged something to main or not — this might still happen.

when this error occurs, only the following message displays to the console: "crbug/1173575, non-JS module files deprecated error". in all occurences of this error that i can find online, people mention it happening while accessing localhost. this leads me to believe that i have setup server/domain/prod relation incorrectly. i bought this domain on hostgator.com and currently host it on vercel, on the free plan. 

i can supply further information if needed. unfortunately, it is so inconsistent that it isn't reproducible. here are some evidences of what happens.

![image](https://user-images.githubusercontent.com/98068247/226324342-3646b13f-dc3b-4ad6-aa1f-6e6ac7c0a13a.png)
![image](https://user-images.githubusercontent.com/98068247/226324456-6d945ef7-2a5f-431d-8032-ab9f8c66c109.png)

feels like a pretty major issue, but i have no clue how to start debugging this. any help is appreciated.

**Comment by OtavioCapila** [comment]
This is related to the provider you are using right now(Vercel). It's possible to create a team and invite some folks to help you to debug? I think a `read` permission is enough.

**Comment by LukeberryPi** [comment]
> This is related to the provider you are using right now(Vercel). It's possible to create a team and invite some folks to help you to debug? I think a `read` permission is enough.

this sounds like a good idea, i'll look into that if the error reoccurs

**Comment by LukeberryPi** [comment]
> This error doesn't seem like code, it seems to be something related to infrastructure. Do you have any log of this hosting? What infrastructure are you using, do you work with containers?

agreed, it doesn't look liike a code error.

i didn't check the hosting logs on the actual site crash, i'll be on the lookout for when/if it happens again.

the infrasctructure is as rudimentary as can be. merge into main => vercel build => prod.

**Comment by LukeberryPi** [comment]
i will pause this issue unless the site breaks again. in reality, we are still around the ~72h mark from first deploy, which is the duration that the domain company mentioned for the dns propagation. this whole ordeal might still be a symptom of that. thanks for the availability @OtavioCapila @osouzajefferson

**Comment by LukeberryPi** [comment]
i'll be closing this tonight and attributing it to delayed dns propagation if we have no further issues with the site becoming inaccessible.
