### ISSUE TITLE
Pwa install button

### ISSUE THREAD

**Issue by jvolima** [LukeberryPi/phived#33]
Hello again, on the PWA pull request you commented on the PWA install button, I can implement it, but I need you to tell me how the design of this button will look, where it will be, and such because the implementation is simple. Or, if you want, I create the component with just the functionality and then you implement the styles and place them wherever you desire.
I'm waiting for the answer.

**Comment by LukeberryPi** [comment]
one of the first things i'd like to bring up is that a user who is currently using the PWA version should not see an install button, correct? is that possible to implement?

furthermore, i think the install button should appear on mobile devices only. ideally, in place of the current "help" button. for a design, this is what i thought of just a simple "inverse" colored button, for some emphasis

light mode:
![image](https://user-images.githubusercontent.com/98068247/226698084-1b5f8a1a-b7af-4b46-9827-b0d40539ff5f.png)

dark mode:
![image](https://user-images.githubusercontent.com/98068247/226697639-7bb9b75f-1073-439c-b255-190d794e91d5.png)

let me know if this makes sense, talk soon

**Comment by jvolima** [comment]
ok, I've already done the styling and the install button works, when you finish designing the new mobile version, contact me on this issue here or on twitter, I'll wait.

**Comment by LukeberryPi** [comment]
continued at https://github.com/LukeberryPi/phived/issues/58
