### ISSUE TITLE
Google not indexing phived website

### ISSUE THREAD

**Issue by rafa-thayto** [LukeberryPi/phived#40]
### What?
Currently, Google isn't indexing the Phived website on google search.

### Solution
- [x] Create the `google-site-verification`  on https://search.google.com/search-console/
- [x] Adds `google-site-verification` meta tag on https://phived.com and other subpages

**Comment by LukeberryPi** [comment]
implemented

![image](https://user-images.githubusercontent.com/98068247/228358804-a670dd55-c0dd-46b8-805e-045b28e53717.png)
