### ISSUE TITLE
layout breaking on mobile

### ISSUE THREAD

**Issue by LukeberryPi** [LukeberryPi/phived#44]
![image](https://user-images.githubusercontent.com/98068247/229008613-a71c0d0a-ba36-4c95-a825-11af9a15c444.png)

this layout break was noticed on mobile devices after the merge of https://github.com/LukeberryPi/phived/pull/41

i suspect it happens because of the following:

1. there is no storedWidth registered
2. the inline styles evaluate to width: 2px
3. the min-width takes action, setting it to *at least* 20% of the viewport
4. resize is inactive on devices < 768px, so it's unfixable

this happens only on actual mobile devices accessing the website. chrome inspect shows no sign of this bug.

i have rolled back to a previous deploy on production.
you can grab this if you want to @YuriSamp, otherwise i'll fix it some other day.

please note that production is currently running https://github.com/LukeberryPi/phived/commit/7ac7b7081e08d37abfd708d2240766da7b2cc4f9.

to debug this you will have to access https://github.com/LukeberryPi/phived/commit/439ac3eab49522e840dabff22f65b4ae6cc61093 locally.

**Comment by Chicarelli** [comment]
I don't get it. When I click at the form border, i'm suposed to be able to resize it?

**Comment by LukeberryPi** [comment]
the issue with resize + localStorage persists, the width seems to updated at uncertain times, generating some unexpected behavior. production currently has the reorder feature and i will hone that before we implement resize again. i will close this issue now and reopen a new one to address this soon.
