### ISSUE TITLE
question mark on end of url

### ISSUE THREAD

**Issue by LukeberryPi** [LukeberryPi/phived#45]
somewhere along the way, any action on the url "https://www.phived.com" concatenated a "/?" to the url, generating "https://www.phived.com/?".

i'm unsure if it impacts SEO, routing or some other functionality. honestly, it just kind of bugs me and i'd like to know where it comes from. i tried fixing it by adding ```<link rel="canonical" href="https://www.phived.com/" />``` it didn't work.

i found this material: https://support.google.com/webmasters/thread/29068832/why-do-i-have-a-url-ending-with-a-question-mark-without-any-parameters?hl=en

please note that production is currently running https://github.com/LukeberryPi/phived/commit/7ac7b7081e08d37abfd708d2240766da7b2cc4f9.

to debug this you will have to access https://github.com/LukeberryPi/phived/commit/439ac3eab49522e840dabff22f65b4ae6cc61093 locally.

**Comment by Chicarelli** [comment]
probably because there isn't preventDefault on onSubmit at <form>.
