### ISSUE TITLE
add animations to `dark mode` and `help` button icons

### ISSUE THREAD

**Issue by datsfilipe** [LukeberryPi/phived#59]
Currently site design is beautiful, but I think the user experience could be enhanced by adding smooth animations to `dark mode` and `help` buttons.

Let me know if you like the idea, I could implement it as you like.

**Comment by LukeberryPi** [comment]
for the icons? such as arrow up rotating 180 to be an arrow down? i like this idea.

feel free to implement it for the help button. if it's smooth, it will be approved :)

i personally wouldn't mess with the dark/light mode button.
