### ISSUE TITLE
Add feature to lock tasks

### ISSUE THREAD

**Issue by datsfilipe** [LukeberryPi/phived#64]
Just an idea I had while using phived:

sometimes you can modify the order of your tasks or even modify the internal text by accident, so, maybe it would be cool to add a feature to lock the task, only allowing the user to click `Done` or unlock it, like Notion does with pages. But it's just an idea.

**Comment by LukeberryPi** [comment]
gostei dessa ideia. vou implementar.

**Comment by LukeberryPi** [comment]
i no longer like this idea but i learned something! will not implement sorry

https://stackoverflow.com/questions/19293321/opposite-of-object-freeze-or-object-seal-in-javascript
