### ISSUE TITLE
High Focus Mode

### ISSUE THREAD

**Issue by MasterTuto** [LukeberryPi/phived#69]
# What is it?

High Focus Mode is a proposal of another way of managing tasks. In simple terms, the rules are:

- Tasks should be assigned a priority
- Higher priority tasks should be placed first
- Users will only see one task at a time, with no way of getting the list saved tasks.

## Why?

In High Focus Mode, users are assigned to tasks rather than choosing a random one to do. Limiting the choices can reduce distractions, and providing more direct quests. See [this article][1] about the known "Paradox of choice" or maybe [Hick's Law][2].

## How?

High Focus Mode must be implemented in a way it keeps Phived as simple as it is, whilst providing a new powerful solution that reduces distractions and maintain user goals.

As I suggestion, I propose a new button next to the logo with some with some Zen reference icon like a Buda or something what when active merges all tasks into two lines.
The first line is the task itself, with a button done, the way it is now.
The second line is a text input an a dropdown/select/slider that describes its priority.

To keep it simple. I suggest a dropdown or select that provides three levels of priorities:

1. Urgency
2. Normal
3. Forgettable

### How many tasks can user add?

Unlimited

### What if the user disables High Focus Mode?

It must delete all user registered tasks, but inform and ask beforehand.

### Isn't it too complex for a simple todo app?

Maybe, it's just a suggestion what can be explored.

### What if the user registers too many Urgent tasks? Will Forgettable tasks never be done?

I think so, it should be sorted first by priority, then by creation.

[1]: https://bootcamp.uxdesign.cc/overcoming-the-paradox-of-choice-in-ui-ux-design-how-to-simplify-user-experience-f80ffe0a0c6c
[2]: https://lawsofux.com/hicks-law/

**Comment by LukeberryPi** [comment]
howdy! i find this idea interesting, but it is not something i'm a) willing to maintain b) confident in the ux win of

thank you for your contribution!
