### ISSUE TITLE
add support for Links in Tasks

### ISSUE THREAD

**Issue by gabrielvsc** [LukeberryPi/phived#72]
Currently, when writing tasks, if a task contains a link, such as "Watch this video: https://www.youtube.com/", I need to copy the link, open another window, and paste.

It would be cool if when I type something like  `"Watch this [video](link)"`  (using Markdown syntax or similar), it automatically converts to  "Watch this [video](link)".

If you need more explanation about this idea, [contact me](https://twitter.com/gabrielvscode),  `nice project :)`

**Comment by LukeberryPi** [comment]
this is a neat idea, thanks for the issue! but i won't code it.

if you want to send a PR, i will definetly approve it if it works smoothly.

**Comment by developerfred** [comment]
We can do this in typescript, to interpret the markedown according to the links, for common services such as X, tiktok and youtube

**Comment by cherryramatisdev** [comment]
maybe this is what we're looking for ? https://github.com/remarkjs/react-markdown

It would be possible to treat the whole task input as markdown and parse it properly using this library

**Comment by mmarcmartins** [comment]
> Maybe this is what we're looking for? https://github.com/remarkjs/react-markdown.
> 
> It would be possible to treat the whole task input as Markdown and parse it properly using this library.
> 
> > PS: Maybe this idea is not the best one because we can't render JSX on the `value` input, and we'll probably need to refactor the whole structure to separate editing/showing. But I'll leave it here anyways.

I'm not sure if this library converts the text to react components while typing, if not we should confirm if that's ok to format the text only when the user hits enter if so I could work on this implementation.

**Comment by LukeberryPi** [comment]
how hard is it to accomplish twitter/x link logic? it feels like the smoothest UX among the current options. example below:

https://github.com/LukeberryPi/phived/assets/98068247/aaf19052-4a4b-4b5b-8b29-ccb468fc458d

**Comment by LukeberryPi** [comment]
some UI ideas. the floating "open external" icon helps with long links (or even a long task that doesn't show any of the link!). i also noticed that on the twitter compose box, when i type "twitter.com" it becomes styled as a link, but isn't actually clickable. it only becomes clickable when you post it. this interaction could be triggered on phived when you blur "from" the task (click another element or the background) to achieve a similar effect.

![1](https://github.com/LukeberryPi/phived/assets/98068247/9cf73a08-9e13-4c67-8ad8-c72bde0aacbd)
![2](https://github.com/LukeberryPi/phived/assets/98068247/18d351d2-8c97-418e-9911-24b0ecf5d484)

**Comment by LukeberryPi** [comment]
the aforementioned twitter compose link interaction illustrated

https://github.com/LukeberryPi/phived/assets/98068247/741b5085-bdce-4f43-bcd7-74da02d0fbff

**Comment by LukeberryPi** [comment]
i did code it after all! some updates. i don't want to support markdown because it sounds a bit overkill. if the goal is to support links, we display a button on hover if there's any links in the task. if you click the button you visit the link in a new tab.

any thoughts? @gabrielvsc 

https://github.com/LukeberryPi/phived/assets/98068247/502b1e8f-c08f-4194-8d37-25f641d2b083

**Comment by LukeberryPi** [comment]
seeking public opinion rn

https://x.com/LukeberryPi/status/1765871164532899853?s=20

**Comment by LukeberryPi** [comment]
this is pretty much solved, closing

https://github.com/LukeberryPi/phived/assets/98068247/4eb7b6f3-9895-4f42-867b-3dfe98ebed1e
