### ISSUE TITLE
QOL: Use `darkMode: media` for automatic theme detection

### ISSUE THREAD

**Issue by guilherssousa** [LukeberryPi/phived#73]
Most of the people don't enjoy when they use Dark mode on virtually anything they use and they enter a new product that shines out loud brightness on your face :c

Although solving this is dead-simple as changing `darkMode` to `media` in [tailwind.config.cjs](https://github.com/LukeberryPi/phived/blob/main/tailwind.config.cjs), since `class` is hard-coded, I decided to open a issue before a PR to check if this is proposital or not

**Comment by JoaoVictor6** [comment]
I can make this @LukeberryPi !
